'use client'
import React from "react"

import figure1 from '../../../public/assets/about/images/figure1.png'
import figure2 from '../../../public/assets/about/images/figure2.png'
import figure3 from '../../../public/assets/about/images/figure3.png'
import figure4 from '../../../public/assets/about/images/figure4.png'
import figure5 from '../../../public/assets/about/images/figure5.png'

import {
  Typography,
} from "@mui/material"

import Grid2 from "@mui/material/Unstable_Grid2/Grid2"

import Image from "next/image"

//Need better text styling

export default function About() {
  return (
    <main>
      <Grid2 container spacing={4} sx={{ maxWidth: "70%", mr: "auto", ml: "auto", mt: "3rem" }}>
        <Grid2 xs={12} lg={6}>
          <Typography variant='h3'>About SCREEN</Typography>
          <Typography variant='h5'>Search Candidate cis-Regulatory Elements by ENCODE</Typography>
          <Typography variant='h4' sx={{pt:"2em"}}>The Encode Encyclopedia</Typography>
          <Typography>
            The ENCODE Encyclopedia comprises two levels of epigenomic and transcriptomic annotations (Figure 1).
            The ground level includes annotations such as peaks and quantifications for individual data types produced
            by the ENCODE uniform processing pipelines. The integrative level contains annotations generated by
            integrating multiple ground-level annotations. The core of the integrative level is the Registry of
            candidate cis-Regulatory Elements (cCREs) which are displayed in SCREEN, a web-based visualization engine
            designed specifically for the Registry. SCREEN allows the user to explore cCREs and investigate how these
            elements relate to other Encyclopedia annotations and raw ENCODE data.
          </Typography>
        </Grid2>
        <Grid2 xs={12} lg={6}>
          {/* Should have better alt text */}
          <Image src={figure1} alt={"The ENCODE Encyclodia"} />
          <Typography>
            Figure 1 | Overview of the ENCODE Encyclopedia with a Registry of candidate cis-regulatory elements.
            The Encyclopedia consists of ground-level and integrative-level of annotations that use data processed
            by the uniform processing pipelines. SCREEN integrates all levels of annotations and raw data and
            allows users to visualize them in the UCSC genome browser.
          </Typography>
        </Grid2>

        <Grid2 xs={12} lg={6}>
          <Typography variant='h4'>The Registry of cCREs</Typography>
          <Typography>
            cCREs are the subset of representative DNase hypersensitivity sites (rDHSs) supported by either histone
            modifications (H3K4me3 and H3K27ac) or CTCF-binding data. We start with 93 million individual DHSs across
            706 DNase-seq profiles in human and 20 million individual DHSs from 173 DNase-seq profiles in mouse. For
            each respective species, we iteratively cluster the DHSs across all profiles and select the DHS with the
            highest signal (read depth normalized signal) as the rDHS for each cluster. This iterative clustering and
            selection process continues until it results in a list of non-overlapping rDHSs—2.2 million rDHSs in human
            and 1.2 rDHSs in mouse—representing all DHSs (Figure 3). We then further selected rDHSs with high DNase signal
            in at least one biosample (defined as a Z-score `{'>'}` 1.64, see details on defining high signal below). Finally,
            from this subset of high signal rDHSs, we selected all elements that were also supported by high H3K4me3,
            H3K27ac, and/or CTCF ChIP-seq signals in concerted biosamples (i.e., samples with complementary assay
            coverage). This resulted in a total of 926,535 human cCREs and 339,815 mouse cCREs (Figure 2).
          </Typography>
          <Typography variant='h5'>Defining high epigenomic signals</Typography>
          <Typography>
            For each rDHS, we computed the Z-scores of the log10 of DNase, H3K4me3, H3K27ac, and CTCF signals in each
            biosample with such data. Z-score computation is necessary for the signals to be comparable across biosamples
            because the uniform processing pipelines for DNase-seq and ChIP-seq data produce different types of signals.
            The DNase-seq signal is in sequencing-depth normalized read counts, whereas the ChIP-seq signal is the fold
            change of ChIP over input. Even for the ChIP-seq signal, which is normalized using a control experiment,
            substantial variation remains in the range of signals among biosamples.
          </Typography>
          <Typography>
            To implement this Z-score normalization, we used the UCSC tool bigWigAverageOverBed to compute the signal for
            each rDHS for a DNase, H3K4me3, H3K27ac, or CTCF experiment. For DNase and CTCF, the signal was averaged across
            the genomic positions in the rDHS. The signals of H3K4me3 and H3K27ac were averaged across an extended region—
            the rDHS plus a 500-bp flanking region on each side—to account for these histone marks at the flanking nucleosomes.
            We then took the log10 of these signals and computed a Z-score for each rDHS compared with all other rDHSs within a
            biosample. rDHSs with a raw signal of 0 were assigned a Z-score of -10. For all analysis we defined `&quot;`high signal`&quot;`
            as a Z-score greater than 1.64, a threshold corresponding to the 95th percentile of a one-tailed test. We define a
            max-Z of a rDHS as the maximum z-score for a signal across all surveyed biosamples.
          </Typography>
        </Grid2>
        <Grid2 xs={12} lg={6}>
          <Image src={figure2} alt={"Selection and classification of cCREs to build the Registry of candidate cis-regulatory elements."} />
          <Typography>
            Figure 2 | Selection and classification of cCREs to build the Registry of candidate cis-regulatory elements. We
            begin by filtering and clustering DNase peaks to create representative DHSs (rDHSs). We then select those rDHSs
            with high DNase signal (maximal Z-score or max-Z across all biosamples with data, see Methods) and high signal
            for at least one other assay (H3K4me3, H3K27ac or CTCF) to be cCREs. In total, we define 926,535 cCREs in human
            and 339,815 cCREs in mouse. Based on combinations of signal and genomic context, we classify cCREs into one of
            these groups: PLS, pELS, dELS, DNase-H3K4me3, or CTCF-only, and their counts are indicated (k: thousand; M: million).
          </Typography>
        </Grid2>
        <Grid2 xs={12}>
          <Typography variant='h4'>Classification of cCREs</Typography>
          <Typography>
            Many uses of cCREs are based on the regulatory role associated with their biochemical signatures. Thus, we putatively
            defined cCREs in one of the following annotation groups based on each element`&apos;`s dominant biochemical signals across all
            available biosamples. Analogous to GENCODE`&apos;`s catalog of genes, which are defined irrespective of their varying expression
            levels and alternative transcripts across different cell types, we provide a general, cell type-agnostic classification
            of cCREs based on the max-Zs as well as its proximity to the nearest annotated TSS:
          </Typography>
          <Typography>
            1. cCREs with promoter-like signatures (cCRE-PLS) fall within 200 bp (center to center) of an annotated GENCODE TSS and
            have high DNase and H3K4me3 signals (evaluated as DNase and H3K4me3 max-Z scores, defined as the maximal DNase or H3K4me3
            Z scores across all biosamples with data; see Methods).
          </Typography>
          <Typography>
            2. cCREs with enhancer-like signatures (cCRE-ELS) have high DNase and H3K27ac max-Z scores and must additionally have a
            low H3K4me3 max-Z score if they are within 200 bp of an annotated TSS. The subset of cCREs-ELS within 2 kb of a TSS is
            denoted proximal (cCRE-pELS), while the remaining subset is denoted distal (cCRE-dELS).
          </Typography>
          <Typography>
            3. DNase-H3K4me3 cCREs have high H3K4me3 max-Z scores but low H3K27ac max-Z scores and do not fall within 200 bp of a TSS.
          </Typography>
          <Typography>
            4. CTCF-only cCREs have high DNase and CTCF max-Z scores and low H3K4me3 and H3K27ac max-Z scores.
          </Typography>
          <Typography>
            In addition to the cell type-agnostic classification described above, we evaluated the biochemical activity of each cCRE
            in each individual cell type using the corresponding DNase, H3K4me3, H3K27ac, and CTCF data (Figure 3). All cCREs with low
            DNase Z-scores in a particular cell type are bundled into one “inactive” state for that cell type; the remaining “active”
            cCREs are divided into eight states according to their epigenetic signal Z-scores, producing nine possible states in total.
            The three groups described above—cCRE-PLS, cCRE-ELS, and CTCF-only cCRE—apply to the active cCREs within a particular cell
            type. Two additional groups are defined with respect to individual cell types: an inactive group, containing all cCREs in
            the inactive state, and a DNase-only group, containing cCREs with high DNase Z-scores but low H3K4me3, H3K27ac, and CTCF
            Z-scores within the cell type. Importantly, while the classification schemes in Figures 2 and 3 place each cCRE into only
            one activity group, the signal strengths for all recorded epigenetic features are retained for each cCRE in the Registry,
            and these can be used for customized searches by users.
          </Typography>
          <Typography>
            We also attempt to make group assignments for cCREs in a particular biosample not fully covered by the four core assays,
            making some approximations. For samples with DNase data, we classify elements using the available marks. For example, if
            a sample lacks H3K27ac its cCREs will be assigned to the PLS and DNase-H3K4me3 groups but not the pELS or dELS groups.
            For biosamples lacking DNase data, we do not have the resolution to identify specific elements. Therefore, for these biosamples,
            we simply label the cCRE as having a high or low signal for every available assay. In these biosamples, cCREs with low H3K4me3,
            H3K27ac, or CTCF signals were labelled “unclassified” because we were unable to classify them as low-DNase without DNase data.
            In both SCREEN and in downloadable files biosamples lacking data are clearly labeled as such.
          </Typography>
        </Grid2>
        <Grid2 xs={12}>
          <Image src={figure3} alt={"Classification of cCREs in GM12878"} />
          <Typography>
            Figure 3 | Classification of cCREs in GM12878. a, Classification of seven groups of cCREs (PLS, pELS, dELS, DNase-H3K4me3,
            CTCF-only, DNase-only, or low-DNase) in GM12878 by their states of high or low H3K4me3, H3K27ac, or CTCF Z-scores in GM12878.
            b, Number of each group of GM12878 cCREs.
          </Typography>
        </Grid2>
        <Grid2 xs={12} lg={6}>
          <Typography variant='h4'>Genomic Footprint of the cCREs</Typography>
          <Typography>
            We analyzed the percentage of the genome covered by each group of cCREs, considering only regions of the genome which are not
            blacklisted (~3.2 billion bases for human and 2.7 billion bases for mouse). In total, 7.9% of the mappable genome is covered by
            cCREs (0.3% by cCREs-PLS, 1.1% by cCREs-pELS, 5.8% by cCREs-dELS, 0.2% by DNase-H3K4me3 cCREs and 0.7% by CTCF-only cCREs)
            and 3.4% of the mappable mouse genome is covered by cCREs (Figure 4). The lower coverage for mouse is due to the smaller number
            of cell types with data to define cCREs.
          </Typography>
        </Grid2>
        <Grid2 xs={12} lg={6}>
          <Image src={figure4} alt={"Genomic coverage of cCREs"} />
          <Typography>
            Figure 4 | Genomic coverage of cCREs. Percentages of the human GRCh38 genome (left) and mouse mm10 genome (right) comprising cCREs
            stratified by cCRE group: PLS in red, pELS in orange, dELS in yellow, DNase-H3K4me3 in pink and CTCF-only in blue.
          </Typography>
        </Grid2>
        <Grid2 xs={12}>
          <Typography variant='h4'>Additional properties of cCREs</Typography>
          <Typography>
            We performed additional analysis on including:
          </Typography>
          <Typography>
            Comprehensiveness of the Registry
          </Typography>
          <Typography>
            Conservation
          </Typography>
          <Typography>
            Overlap with other epigenomic and transcriptomic data
          </Typography>
          <Typography>
            Experimental validation from mouse transgenic assays
          </Typography>
          <Typography>
            Details and results from these analyses can be found at our companion website, http://encyclopedia.wenglab.org/.
          </Typography>
        </Grid2>
        <Grid2 xs={12}>
          <Typography variant='h4'>Integration with ground level annotations</Typography>
          <Typography>
            In addition to hosting the Registry of cCREs, SCREEN also integrates the ground level Encyclopedia annotations. Under the cCRE
            Details page for each cCRE are the overlapping ground level annotations with links to their derived experiments. Additionally,
            some annotations, such as histone mark and TF ChIP-seq peaks, gene expression, and RAMPAGE transcription levels are highlighted
            further with specific tabs under the cCRE Details page.
          </Typography>
        </Grid2>
        <Grid2 xs={12}>
          <Typography variant='h4'>Using cCREs to Interpret GWAS Variants</Typography>
          <Typography variant='h5'>Curating GWAS Results</Typography>
          <Typography>
            We downloaded associations reported in the NHGRI-EBI genome-wide association studies (GWAS) catalog as of January 1, 2019. Because
            mixed populations complicate linkage disequilibrium (LD) structures, we only selected studies that were performed on a single
            population. For each study, we downloaded all reported SNPs (p `{'>'}` 10-6), even those that were just under genome wide significance.
            We then intersected all reported SNPs and SNPs in high LD (r2 `{'>'}` 0.7), with GRCh38 cCREs. These results are available through the
            SCREEN GWAS app.
          </Typography>
          <Typography variant='h5'>Determining Cell Types with cCREs Enriched in GWAS SNPs</Typography>
          <Typography>
            For studies with more than 25 lead SNPs, we performed biosample enrichment analysis. For each study, we generated a matching set of
            control SNPs as follows: for each SNP in the study (p-value `{'>'}` 10-6) we selected a SNP on Illumina and Affymetrix SNP chips that fell
            within the same population-specific minor allele frequency (MAF) quartile and the same distance to TSS quartile. We repeated this
            process 500 times, generating 500 random control SNPs for each GWAS SNP. Then, for both GWAS and control SNPs, we retrieved all SNPs
            in high linkage disequilibrium (LD r2 `{'>'}` 0.7), creating LD groups. This method was adapted and modified from the Uncovering Enrichment
            through Simulation (UES) method developed by the Klein Lab (Hayes et al. 2015).
          </Typography>
          <Typography>
            To assess whether the cCREs in a biosample were enriched in the GWAS SNPs, we intersected GWAS and control LD groups with cCREs with an
            H3K27ac Z-score `{'>'}` 1.64 in the biosample. To avoid overcounting, we pruned the overlaps, counting each LD group once per biosample.
            We modified the UES method by calculating p-values from Z-scores for performing statistical testing. We calculated enrichment for overlapping
            cCREs by comparing the GWAS LD groups with the 500 matched controls. Finally, we applied a false discovery rate threshold of 5% to each study.
          </Typography>
        </Grid2>
        <Grid2 xs={12}>
          <Image src={figure5} alt={"Enrichment of GWAS SNPs in biosample specific cCREs."} />
          <Typography>
            Figure 5 | Enrichment of GWAS SNPs in biosample specific cCREs. SCREEN reports the percentage of LD blocks of a GWAS with at least one SNP
            overlapping a cCRE. Biosamples are ranked by enrichment of SNP-overlapping cCREs with high H3K27ac signals. Top cell and tissue types are
            displayed here for each study.
          </Typography>
        </Grid2>
        <Grid2 xs={12} id="tutorials">
          <Typography variant='h3'>Tutorials</Typography>
        </Grid2>
        <Grid2 xs={12} id="api-documentation">
          <Typography variant='h3'>API Documentation</Typography>
        </Grid2>
        <Grid2 xs={12} id="versions">
          <Typography variant='h3'>Versions</Typography>
        </Grid2>
        <Grid2 xs={12} id="ucsc-genome-browser">
          <Typography variant='h3'>UCSC Genome Browser</Typography>
        </Grid2>
        <Grid2 xs={12} id="contact-us">
          <Typography variant='h3'>Contact Us</Typography>
        </Grid2>
      </Grid2>
    </main>
  )
}
