site_name: SCREEN GraphQL API
repo_name: SCREEN2.0
repo_url: https://github.com/weng-lab/SCREEN2.0
site_description: "A GraphQL API to access SCREEN data"
site_author: Nishigandha Phalke
remote_branch: main

copyright: 'Copyright &copy; Weng Lab, Moore Lab 2024'

theme:
  name: 'readthedocs'

nav:
  - 'Home': index.md
  - 'Getting started':
    - 'Command-line': getting_started/command_line.md
    - 'Python': getting_started/python.md
    - 'Javascript': getting_started/javascript.md
  - 'Queries':
    - 'Searching cCREs': queries/ccres.md
    - 'cCRE details': queries/ccredetails.md
    - 'Gene expression': queries/geneexpression.md
    - 'GWAS': queries/gwas.md
    - 'Rampage': queries/rampage.md
    - 'Suggest cCRE, genes and SNPs on search':  queries/searchautocomplete.md
    - 'Functional Characterization':  queries/functionalcharacterizationdata.md