apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-screen
  labels:
    app: nextjs-screen
spec:
  selector:
    matchLabels:
      app: nextjs-screen
      tier: web
  template:
    metadata:
      labels:
        app: nextjs-screen
        tier: web
    spec:
      containers:
      - name: nextjs-screen-app
        image: gcr.io/devenv-215523/screen-2.0-ui:${SERVICE_VERSION}
        ports:
        - containerPort: 3000
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: nextjs-screen-cert
spec:
  domains:
    - screen.2.0.wenglab.org
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-screen
  annotations:
    kubernetes.io/ingress.global-static-ip-name: screen-new-api-external-ip
    kubernetes.io/ingress.allow-http: "true"
    networking.gke.io/managed-certificates: nextjs-screen-cert
  labels:
    app: nextjs-screen
spec:
  defaultBackend:
    service:
      name: nextjs-screen-backend
      port:
        number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-screen-backend
  labels:
    app: nextjs-screen
spec:
  type: NodePort
  selector:
    app: nextjs-screen
    tier: web
  ports:
  - port: 8080
    targetPort: 3000