name: Deploy Next.js to Github Pages

on:
  push:
    branches: [ main ]
  #Allows manual running of the workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./screen2.0
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          # update the Node version to meet your needs
          node-version: 18
          cache: yarn
          cache-dependency-path: screen2.0/yarn.lock
      # Build and export, add .nojekyll to out/. See "Configure Build" at https://www.viget.com/articles/host-build-and-deploy-next-js-projects-on-github-pages/
      - name: Build
        run: |
          ls -la
          yarn install
          yarn build
          yarn export
          touch out/.nojekyll
      - name: Deploy
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@v4.4.1 
        with:
          branch: gh-pages
          folder: out